### ISSUE TITLE
Padding Select2

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/system-budgeting#16]
![image](https://user-images.githubusercontent.com/11961119/53695999-7aeec780-3dfd-11e9-830d-06914a18fd7d.png)

Perbaiki padding select2

**Comment by syauqiahmd** [comment]
paddingnya done 👍 ,tapi style focus pada select2 undone 👎

**Comment by FaruqRahmadani** [comment]
kalo kada salah ini sdh beres lah?

**Comment by syauqiahmd** [comment]
beres mun soal paddingnya, ku close ja lak dulu, yg blum cuman lining boxnya aja
